schema = {
    "report_segment_loads": """
|-- total_loads: int (nullable = true)
|-- total_daily_uniques: int (nullable = true)
|-- total_monthly_uniques: int (nullable = true)
|-- advertiser_id: string (nullable = true)
|-- segment_id: string (nullable = true)
|-- segment_name: string (nullable = true)
|-- datehour: string (nullable = true)
|-- dayserial_numeric: long (nullable = true)
|-- category: string (nullable = true)
|-- subcategory: string (nullable = true)
|-- advertiser_name: string (nullable = true)
|-- day_numeric: long (nullable = true)
""",
    "report_device_overlap": """
|-- geo_country: string (nullable = true)
|-- advertiser_id: string (nullable = true)
|-- advertiser_name: string (nullable = true)
|-- segment_id: string (nullable = true)
|-- segment_name: string (nullable = true)
|-- device_type: string (nullable = true)
|-- device_model_id: string (nullable = true)
|-- device_model_name: string (nullable = true)
|-- device_make_name: string (nullable = true)
|-- converted_count: int (nullable = true)
|-- total_count: int (nullable = true)
|-- percent_converted: double (nullable = true)
|-- dayserial_numeric: long (nullable = true)
|-- category: string (nullable = true)
|-- subcategory: string (nullable = true)
|-- day_numeric: long (nullable = true)
""",
    "report_dpi_srsv2_high_volume_domains": """
|-- dayserial_numeric: long (nullable = true)
|-- sitedomain: string (nullable = true)
|-- degeocountry: string (nullable = true)
|-- word: string (nullable = true)
|-- segment_id: string (nullable = true)
|-- segment_name: string (nullable = true)
|-- num_conv_users: long (nullable = true)
|-- conv_users_visits: long (nullable = true)
|-- num_users_all: long (nullable = true)
|-- users_visits_all: long (nullable = true)
|-- user_conv_ratio: double (nullable = true)
|-- conv_freq: double (nullable = true)
|-- all_freq: double (nullable = true)
|-- advertiser_id: string (nullable = true)
|-- advertiser_name: string (nullable = true)
|-- category: string (nullable = true)
|-- subcategory: string (nullable = true)
|-- data_center: string (nullable = true)
|-- cluster: int (nullable = true)
|-- day_numeric: long (nullable = true)
""",
}
